### ISSUE TITLE
[US6] Internalizing the Scrum Framework

### ISSUE THREAD

**Issue by abdullahkhan91** [rhashimo/a3-education#19]
As a student who is learning about the Scrum framework,
I want to intentionally incorporate the principles and processes of Scrum into Sprint 2
so that it becomes second nature to me and I feel prepared to use Scrum in my future projects

- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

**Comment by abdullahkhan91** [comment]
[x] Have a storytime meeting to add new user stories, pull up existing stories from the backlog, and organize them by splitting, merging, or removing
[x] Have a thorough sprint planning meeting in which each story is broken down into tasks, the tasks are discussed by the team, and planning poker is used to assign story-points
[x] Each team member should do at least one task with another member through pair coding
[x] Create and update a burndown chart

**Comment by abdullahkhan91** [comment]
**Definition of Done**
- [ ] All the three members will upload videos in which they state the four core values of the Agile Manifesto, give one example of how they incorporated a value into their workflow for 691, and briefly state the four main meetings of the Scrum framework and describe their purpose.

**Comment by abdullahkhan91** [comment]
> **Definition of Done**
> 
> * [ ]  All the three members will submit reflections as comments here in which they give one example of how they incorporated a core value of the Agile Manifesto into their 691 project.

_Reflection about agile core value: Responding to Change over Following a Plan_
At the end of sprint 1, I had created a stacked and grouped bar chart (by cleaning and tabulating data in STATA, importing output to Excel and creating the graphic there). The plan at the beginning of Sprint 2 was to convert that to a D3 visualization by switching the data and making other minor tweaks in an existing D3 stacked and grouped bar chart. I, however, couldn’t find such a visualization online, so I responded to the change by taking the following steps: 
1.	I first copied the code for a stacked D3 bar chart into my local repository and tried tweaking the JavaScript to create spaces between the bars to give the appearance of grouping. 
2.	When I was unable to figure out the JavaScript, I took a different approach and modified the data.tsv file by inserting empty columns between the groups.
It wasn’t the most elegant solution but the result looked fine so I stuck with it and consciously decided not to spend time trying to learn how to tweak the JavaScript code to group the bars.

**Comment by rhashimo** [comment]
> **Definition of Done**
> 
> * [ ]  All the three members will submit reflections as comments here in which they give one example of how they incorporated a core value of the Agile Manifesto into their 691 project.

_Reflection about agile core value: Customer collaboration over contract negotiation_
In each sprint, we developed detailed user stories and worked based on them. Also, while we are working on the project, we asked actual users (researchers, students, and so on) to improve the working software. I believe this core value is the key to build the working software in such a short time period.

**Comment by AncitoEtienne** [comment]
_Reflection about agile core value: Working software over comprehensive documentation_
While developing the website, and in my page in particular, I made sure that all the graphics showed up well and the page was consistent with the layout and structure of other pages rather than focusing on documentation extensively each step of the process. After making sure, the website was working well and my page was how I envisioned it, I began working on documentation comprehensively my process.
